version: "3"
networks:
  wis2.wmo.int:

services:
    web:
      image: nginx     
      volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf
       - ./conf.d:/etc/nginx/conf.d
       - ./ssl:/etc/nginix/ssl
       - ./CA/node_ch.crt:/etc/nginx/ssl/node.crt
       - ./CA/node_ch.key:/etc/nginx/ssl/node.key
       - ./CA/wisca.crt:/etc/nginx/ssl/wisca.crt
       - ./index.html:/etc/nginx/html/index.html
       
      ports:
       - "80:80"
       - "443:443"
    
      networks:
        wis2.wmo.int:  
            aliases:
               - node-ch.wis2.wmo.int
       
   
    mosquitto:
      image: eclipse-mosquitto:2
      volumes:
       - ./mosquitto.conf/:/mosquitto/config/mosquitto.conf
       - ./acl_file:/etc/mosquitto/acl_file
       - ./CA/node_ch.crt:/etc/mosquitto/node.crt
       - ./CA/node_ch.key:/etc/mosquitto/node.key
       - ./CA/wisca.crt:/etc/mosquitto/wisca.crt
       
      ports:
       - 8883:8883
       - 9001:9001
      
      networks:
        wis2.wmo.int:    

    python:
      build: .
      
      stdin_open: true # docker run -i
      tty: true
      
      volumes:
       - ./test_certificates.py:/usr/src/app/test_certificates.py
       - ./CA/gb_fr.crt:/usr/src/app/gb_fr.crt
       - ./CA/gb_fr.key:/usr/src/app/gb_fr.key
       - ./CA/gb_ma.crt:/usr/src/app/gb_ma.crt
       - ./CA/gb_ma.key:/usr/src/app/gb_ma.key
       - ./CA/gb_fr_fake.crt:/usr/src/app/gb_fr_fake.crt
       - ./CA/wisca.crt:/usr/src/app/wisca.crt
                                  
      command: bash -c "sleep 10; pytest"
      
      networks:
        wis2.wmo.int:    

    python-publisher:
      build: .
      
      stdin_open: true # docker run -i
      tty: true
      
      volumes:
       - ./keep_publishing.py:/usr/src/app/keep_publishing.py
       - ./CA/node_ch.crt:/usr/src/app/node_ch.crt
       - ./CA/node_ch.key:/usr/src/app/node_ch.key
       - ./CA/wisca.crt:/usr/src/app/wisca.crt       
             
      command: bash -c "python keep_publishing.py"
      
      networks:
        wis2.wmo.int:    
